language: ruby
rvm:
  - "2.0.0"
  - "2.1.0"
  - "2.2.0"
before_script:
  - gem install bindeps
  - bundle install
  - bundle exec rake compile
  - bundle exec bin/transrate --install-deps
os:
  - linux
  - osx
matrix:
  allow_failures:
    - os: osx
    - rvm: "2.2.0"
